repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.4.0
  hooks:
    - id: go-unit-tests
    - id: go-build
    - id: golangci-lint
    - id: go-mod-tidy
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v6.0.0
  hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ['@commitlint/config-conventional']
