name: Go

on:
  push:
    branches: ['*']
    tags: ['v*']
  pull_request:
    branches: ['*']

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.20", "1.19", "1.18"]

    steps:

    - name: Setup Go environment
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Load cached dependencies
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download Dependencies
      run: go mod download

    - name: Test
      if: matrix.latest
      run: make test

  lint:
    name: GolangCI Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.20", "1.19", "1.18"]

    steps:
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
        cache: false
    - name: Checkout code
      uses: actions/checkout@v3
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
